### PR TITLE
Add email forwarding information

### PR DESCRIPTION
**Pull request by sulmoJ**
### Task
- [ ] New Documentation
- [x] Fix Content
- [ ] Etc (CI/CD Workflow)

### Description
This request was made for npm 2FA.

### CODE REVIEW

**Comment by choonho** [comment]
Email verification was sent to "tjdah0853@gmail.com,pyt4105@gmail.com"
Please confirm email

**Comment by choonho** [comment]
Did you receive test email?

**Comment by sulmoJ** [comment]
Yes!! 
image

**Comment by sulmoJ** [comment]
When I connect to the link in the confirmation email I received from AWS, I get the [SES document](https://aws.amazon.com/ko/ses/details/). When I connect like this, is it confirmed??

**Comment by sulmoJ** [comment]
Yes!!

2024년 7월 9일 (화) 오전 11:18, Choonho Son ***@***.***>님이 작성:

**Comment by choonho** [comment]
> When I connect to the link in the confirmation email I received from AWS, I get the [SES document](https://aws.amazon.com/ko/ses/details/). When I connect like this, is it confirmed??

Yes. Just click is enough

**Comment by sulmoJ** [comment]
I tried logging in to npm for One-time Password to receive. But I didn't get an email to my account. What should I do?

**Comment by choonho** [comment]
There is no problem to receiving admin@cloudforet.io The problem occurs at npm site.

**Comment by choonho** [comment]
Can you test another site which uses admin@cloudforet.io?

**Comment by choonho** [comment]
When I test admin@cloudforet.io at npmjs site, we got the 403 Forbidden. The account may be disabled. You have to contact support center.

**Comment by sulmoJ** [comment]
I tested it with both PyPI and Docker Hub, and only PyPI was received. I'll check it again following your guidance!

**Pull request merged**
